### ISSUE TITLE
Figwheel template om breaks when compiling advanced optimizations

### ISSUE THREAD

**Issue by daviddpark** [bhauman/figwheel-template#16]
I am trying to move my om application, based on the figwheel template from the Basic Om tutorial toward production readiness. I am sure there is something simple that I am missing, but attempting to use the min cljsbuild in the figwheel template breaks.

To reproduce, run the following commands:

```
lein new figwheel om-tut -- --om
cd om-tut
lein figwheel
```

Verify that the application responds at http://localhost:3449, then

```
CTRL-C
lein clean
lein cljsbuild once min
cd resources/public/
python -m SimpleHTTPServer
```
Verify that the page is served at http://localhost:8000, but see the Javascript console:
Uncaught Error: Assert failed: No target specified to om.core/root
(not (nil? target))

**Comment by bhauman** [comment]
Peter, this error indicates that the dom element where you are intending to mount the app is not available.  Do you have an div#app element in your index.html?

I just repeated these same steps and it worked fine.  Did you actually do these steps explicitly or do these steps approximate what you think would cause the error?

**Comment by daviddpark** [comment]
You are correct that it is working correctly.

Yesterday, I literally copied the commands out of running history in my terminal session into the issue and removed the history identifiers. I reproduced this yesterday, but today I can not. 

Sorry to waste your time.

**Comment by bhauman** [comment]
Hey no worries.

Glad you are giving it a try :)
