### ISSUE TITLE
Non working OOTB template: Clojure version issues

### ISSUE THREAD

**Issue by AlexAti** [bhauman/figwheel-template#19]
Hello,

I've just made lein new figwheel <name> -- --reagent and the created project is not working.

It's an easy fix: the clojurescript version of the template in: https://github.com/bhauman/figwheel-template/blob/master/src/leiningen/new/figwheel/project.clj

needs a clojure version bump: https://github.com/bhauman/lein-figwheel/issues/152

I changed it to "1.7.0-RC1" and afterwards, "lein figwheel" just works, as expected.

Another thing I noticed is that my project did not get README.md, for whatever reason.

**Comment by bhauman** [comment]
Just deployed the fixed version thanks!!
