### ISSUE TITLE
Using latest react from cljsjs

### ISSUE THREAD

**Issue by joakin** [bhauman/figwheel-template#22]
Thanks for this wonderful template :smile: :+1: (and for figwheel). Been using it quite a lot.

Would you be open to bringing the latest react with addons when using `--reagent`? (`0.14` instead of the `0.13` included in reagent).

Something like this:
https://github.com/joakin/cljs-browser-repl/blob/master/project.clj#L10-L11

Not sure if that would be useful for om.

**Comment by bensu** [comment]
Only to clarify your last point: it wouldn't be useful for om since it om versions have *some* react version dependency (many bug fixes are made with specific versions in mind).

**Comment by bhauman** [comment]
Thanks! I'm glad you like it.   It does seem best to let the various libraries dictate their dependencies.

Folks who want react with addons can make the needed adjustments. :)

**Comment by joakin** [comment]
Awesome, thanks for the comments!
