### ISSUE TITLE
:min profile should not use :advanced build :optimizations

### ISSUE THREAD

**Issue by jessjohn** [bhauman/figwheel-template#24]
```
~/Documents $ lein new figwheel hello-world
Generating fresh 'lein new' figwheel project.
~/Documents $ cd hello-world/
~/Documents/hello-world $ lein figwheel min
Figwheel Config Error (in project.clj) - you have build :optimizations set to something other than :none
~/Documents/hello-world $
```

Looks like figwheel no longer supports `:compiler {:optimizations :advanced}`.

**Comment by bhauman** [comment]
figwheel never supported advanced builds

**Comment by jessjohn** [comment]
Sorry, I'm confused then... 
Why does figwheel-template include a `:min` profile that has never run with figwheel?

**Comment by bhauman** [comment]
Sorry about my short answer. I was tired last night.  I added the min profile as and example.  

You can compile the min profile with 
lein cljsbuild once min 

Every project normally needs a production compile config. And people need to see that :figwheel true isn't part of that config.

**Comment by jessjohn** [comment]
No worries. That makes sense, thanks for clarifying Bruce. :)
