### ISSUE TITLE
running om.next fails with 'Cannot read property 'render' of undefined'.

### ISSUE THREAD

**Issue by tokomakoma123** [bhauman/figwheel-template#32]
Hi,

I am testing om-next using figwheel-template.
I have created a new project as follows:

```bash
lein new figwheel om-next-example
```

And I've changed the version of om to 1.0.0-alpha36.

```clj
[org.omcljs/om "1.0.0-alpha36"]
```

Then, I've changed core.cljs as below:

```clj
(ns om-next-example.core
  (:require [goog.dom :as gdom]
            [om.next :as om :refer-macros [defui]]
            [om.dom :as dom]))

(defui HelloWorld
  Object
  (render [this]
    (dom/div nil "Hello, world!")))

(def hello (om/factory HelloWorld))

(js/ReactDOM.render (hello) (gdom/getElement "app"))

(defn on-js-reload []
  ;; optionally touch your app-state to force rerendering depending on
  ;; your application
  ;; (swap! app-state update-in [:__figwheel_counter] inc)
```

I started figwheel and paste om-next code in REPL.

```bash
lein figwheel
```

```
cljs.user=> (ns om-next-example.core
  (:require [goog.dom :as gdom]
            [om.next :as om :refer-macros [defui]]
            [om.dom :as dom]))
nil
om-next-example.core=> (defui HelloWorld
  Object
  (render [this]
    (dom/div nil "Hello, world!")))
#object[Function "function (this__32416__auto__,writer__32417__auto__,opt__32418__auto__){
return cljs.core._write.call(null,writer__32417__auto__,"om-next-example.core/HelloWorld");
}"]
om-next-example.core=> (def hello (om/factory HelloWorld))
#'om-next-example.core/hello
om-next-example.core=> (js/ReactDOM.render (hello) (gdom/getElement "app"))
#object[TypeError TypeError: Cannot read property 'render' of undefined]
nil
```

Is there anything wrong in my steps to run om.next  ?

**Comment by bensu** [comment]
It looks like `ReactDOM` is missing. Check the current `react` dependency with `lein deps :tree`. If it is not the latest (or the one that should be used with your version of `om.next`), explicitly specify the correct one as a dependency in `project.clj`.

A quick look to [om's project .clj](https://github.com/omcljs/om/blob/master/project.clj) suggests:

```clj
:dependencies [
                         ...
                         [cljsjs/react "15.0.1-1"]
                         [cljsjs/react-dom "15.0.1-1"]
```

**Comment by tokomakoma123** [comment]
@bensu Thank you for your reply.

lein deps :tree showed the following.

```clj
 [org.omcljs/om "1.0.0-alpha36"]
   [cljsjs/react-dom "15.0.1-1"]

 [sablono "0.3.6"]
   [cljsjs/react "0.13.3-0"]
```

I removed sablono from dependencies generated by figwheel template and 
start 'lein figwheel', then it worked !

**Comment by bensu** [comment]
Great! If you wanted to use `sablono` then you could add the latest version. In any case, I'm glad this issue is solved.

**Comment by tokomakoma123** [comment]
@bensu I did it as follows and it also works fine !

```
 [sablono "0.3.6" :exclusions [cljsjs/react]]
```

Now I feel very fun and comfortable for writing cljs  code with figwheel template !
