### ISSUE TITLE
npx problem on Windows

### ISSUE THREAD

**Issue by zmej-serow** [bhauman/figwheel-template#46]
Is it possible to add somehow check for operating system while creating template?
I'm too fresh to do it by myself yet :)

The issue: unfortunately, on Windows we cannot call npx as `npx`, it is called as `npx.cmd`.
So if we want [template](https://github.com/bhauman/figwheel-template/blob/master/src/leiningen/new/figwheel/project.clj) to work properly, we have to [change manually](https://clojureverse.org/t/cljs-project-using-figwheel-on-windows/6079/7) `npx` to `npx.cmd` here (42th and 43th lines):

```
{{#bundle?}}:bundle-cmd {:none ["npx" "webpack" "--mode=development"]
                                        :default ["npx" "webpack"]}
```

**Comment by bhauman** [comment]
Thanks for pointing this out. Super helpful :)
