### ISSUE TITLE
Assumption of webpack and bundling as default breaks figwheel template 

### ISSUE THREAD

**Issue by joinr** [bhauman/figwheel-template#51]
I know the recommendation is to use figwheel-main, however we have new users leveraging older figwheel tutorials.  per https://clojureverse.org/t/error-in-figwheel-can-it-be-fixed/7750

It looks like the +no-bundle option came later (prior to migration to figwheel-main), where before it was the default.  So now when new users follow the old style `lein new figwheel`, they get a jacked up project if they don't have npm and webpack installed.  There's no message or indication of the (now) required installation of npm and webpack.

In case this isn't patched due to its age, for folks running into this problem following old figwheel tutorials, you can probably fix your issues with the following invocation, assuming the project is called `figtest`:

lein new figwheel  figtest -- +no-bundle

That will behave like figwheel "classic" which is what most of the legacy tutorials and blog posts will indicate.

**Comment by bhauman** [comment]
Yeah this makes sense, I've changed it so that +bundle indicates a need for npm.
