### ISSUE TITLE
Simplify script tags in index.html

### ISSUE THREAD

**Issue by bensu** [bhauman/figwheel-template#7]
This is more an enhancement than an issue.

After bumping up the Clojurescript version it should be possible to write:

     <script src="js/compiled/{{name}}.js" type="text/javascript"></script>

Instead of using goog.require

I tried it but it doesn't work since it wants to load files from `resources/public/js/compiled` when the server resource root is on `public`. When (if) I figure it out, the dev and min build will need the same markup, allowing advanced compilation out of the box.

**Comment by bhauman** [comment]
This is because an :asset-path is needed for a compiler option.

https://github.com/clojure/clojurescript/wiki/Compiler-Options#asset-path

**Comment by bensu** [comment]
Solve in commit 2af5c394fdf5f1d3338ca075cfd618e4e60b00ec
